
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Obsidian Drape Coat',
    description: 'A monolithic Italian wool architecture designed to compress ambient presence and assert absolute silhouette dominance.',
    statement: 'Absolute weight. Zero friction.',
    price: 890,
    originalPrice: 1250,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1000&auto=format&fit=crop',
    mood: 'Luxe',
    scarcityCount: 3,
    socialCount: 412,
    fitConfidence: 94,
    category: 'Outerwear',
    styleTag: 'Old Money',
    emotionTag: 'Confidence',
    isPreOrder: false,
    lastMonthSales: 45
  },
  {
    id: '2',
    name: 'Ghost Knit Sweater',
    description: 'Neuro-adaptive deconstructed mohair, engineered with raw-edge geometry to signal an intentional disregard for standard symmetry.',
    statement: 'Fragmented by design.',
    price: 320,
    originalPrice: 480,
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=1000&auto=format&fit=crop',
    mood: 'Minimal',
    scarcityCount: 12,
    socialCount: 42,
    fitConfidence: 88,
    category: 'Apparel',
    styleTag: 'Minimal',
    emotionTag: 'Serenity',
    isPreOrder: false,
    lastMonthSales: 2
  },
  {
    id: '3',
    name: 'Cargo Vandal Trousers',
    description: 'Sub-dermal technical nylon housing a multi-strap kinetic lattice for high-stakes urban navigation and structural intimidation.',
    statement: 'Geometry in motion.',
    price: 450,
    originalPrice: 620,
    image: 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?q=80&w=1000&auto=format&fit=crop',
    mood: 'Street',
    scarcityCount: 7,
    socialCount: 856,
    fitConfidence: 92,
    category: 'Apparel',
    styleTag: 'Street',
    emotionTag: 'Intimidation',
    isPreOrder: false,
    lastMonthSales: 120
  },
  {
    id: '4',
    name: 'Venom Leather Boots',
    description: 'High-gloss calfskin conduits featuring a brutalist square-toe chassis, engineered for high-velocity terrestrial advancement.',
    statement: 'Claim the ground.',
    price: 640,
    originalPrice: 910,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop',
    mood: 'Bold',
    scarcityCount: 15,
    socialCount: 24,
    fitConfidence: 91,
    category: 'Footwear',
    styleTag: 'Avant-Garde',
    emotionTag: 'Allure',
    isPreOrder: false,
    lastMonthSales: 1
  },
  {
    id: '5',
    name: 'Neural Visor Goggles',
    description: 'Optical shielding unit with carbon-lattice framework and adaptive phototropic sensors, designed to curate the wearer\'s reality.',
    statement: 'Reality is a choice.',
    price: 1200,
    originalPrice: 1650,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=1000&auto=format&fit=crop',
    mood: 'Bold',
    scarcityCount: 2,
    socialCount: 104,
    fitConfidence: 99,
    category: 'Accessories',
    styleTag: 'Cyberpunk',
    emotionTag: 'Rebellion',
    isPreOrder: false,
    lastMonthSales: 30
  },
  {
    id: '6',
    name: 'Titanium Signet Ring',
    description: 'A forged titanium status-marker featuring an unrefined sapphire core, designed as a physical encryption key for the elite collective.',
    statement: 'The weight of authority.',
    price: 550,
    originalPrice: 850,
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop',
    mood: 'Luxe',
    scarcityCount: 8,
    socialCount: 341,
    fitConfidence: 100,
    category: 'Jewelry',
    styleTag: 'Quiet Luxury',
    emotionTag: 'Euphoria',
    isPreOrder: false,
    lastMonthSales: 15
  }
];

export const STATUS_PROGRESSION = {
  Observer: { min: 0, max: 1000, color: 'text-stone-400' },
  Insider: { min: 1001, max: 5000, color: 'text-white' },
  Trendsetter: { min: 5001, max: 20000, color: 'text-amber-500' },
  Icon: { min: 20001, max: Infinity, color: 'text-indigo-400' }
};
